image: Visual Studio 2019
clone_folder: C:\TBuild\tdesktop
test: off
deploy: off

environment:
  GYP_MSVS_OVERRIDE_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\'
  GYP_MSVS_VERSION: 2019
  matrix:
   - BUILD_VERSION:
   - BUILD_VERSION: disable_register_custom_scheme
   - BUILD_VERSION: disable_crash_reports
   - BUILD_VERSION: disable_network_proxy

matrix:
  fast_finish: true

before_build:
  - .\.appveyor\install.bat

build:
  project: Telegram\Telegreat.sln

artifacts:
  - path: out\Debug\Telegreat.exe
    name: Telegreat_debug.exe
  - path: out\Debug\Telegreat.exe.pdb
    name: Telegreat_debug.exe.pdb
