image: Visual Studio 2017
clone_folder: C:\TBuild\tdesktop
test: off
clone_depth: 1
configuration: Release

environment:
  matrix:
   - BUILD_VERSION:

matrix:
  fast_finish: true

before_build:
  - .\.appveyor\install.bat

build:
  project: Telegram\Telegreat.sln

artifacts:
  - path: out\*
    name: files

deploy:
  - provider: GitHub
    auth_token: ""
    repository: Sea-n/Telegreat
    prerelease: true
    artifact: files
    on:
      branch: dev
